#**Data Preprocessing**

**Load the dataset.**

In [31]:
import pandas as pd

df = pd.read_csv("/content/student_performance.csv")

**Encode any categorical columns if required.**

In [32]:
print(df.columns)

df.shape

Index(['Student_ID', 'Name', 'Age', 'Program', 'Python', 'Mathematics',
       'Statistics', 'Machine_Learning', 'Attendance'],
      dtype='object')

(20, 9)

In [33]:
df.dtypes

Student_ID          object
Name                object
Age                  int64
Program             object
Python               int64
Mathematics          int64
Statistics           int64
Machine_Learning     int64
Attendance           int64
dtype: object

In [34]:
from sklearn.preprocessing import LabelEncoder

obj = LabelEncoder()

df['Name'] = obj.fit_transform(df["Name"])
df["Program"] = obj.fit_transform(df["Program"])

**Create a new column named Average_Score (if not already created).**

In [35]:
df["Average_Score"] = df.iloc[: , 4:8].mean(axis=1)

**Select appropriate feature columns (X) and target column (y).**

In [36]:
X = df.drop(columns=["Average_Score","Student_ID" , "Name"])
# Because training a model does not depend on students ID and his/her name so i dropped it
y = df["Average_Score"]

**Split the dataset into Training (80%) and Testing (20%).**

In [37]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size=0.2 , random_state = 42
)

**Apply feature scaling where appropriate.**

In [38]:
X.head()
# Since Data is roughhly balanced so i skipped the feature scaling as there is no dominant feature.

   Age  Program  Python  Mathematics  Statistics  Machine_Learning  Attendance
0   20        0      85           78          92                88          95
1   21        0      72           75          70                80          90
2   22        2      90           88          91                93          96
3   20        1      65           70          68                72          85
4   21        0      78           82          80                76          88